# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #- name: Install MSVC compiler
    #    uses: ilammy/msvc-dev-cmd
    #    with:
          # 14.1 is for vs2017, 14.2 is vs2019, following the upstream vcpkg build from Qv2ray-deps repo
    #      toolset: 14.2
    #      arch: x64

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/build/Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.0'
        host: 'windows-lastest'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        dir: '${{ github.workspace }}/build/'
        install-deps: 'true'
        modules: 'qtserialport'
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        aqtversion: '==0.9.4'
        py7zrversion: '==0.9.1'
        extra: '--external 7z'

    # Runs a set of commands using the runners shell
    - name: Build
      run: |
        qmake
        make
    
    - name: Upload Artifact
      uses: actions/upload-artifact@master
        with:
          name: smart_thermometer_ui.exe
          path: smart_thermometer_ui.exe
    
        
